include $(TOPDIR)/rules.mk

PKG_NAME:=bad-head
PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/example/bad-head.git
PKG_SOURCE_VERSION:=HEAD
PKG_MIRROR_HASH:=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
