src-git-full base https://git.openwrt.org/openwrt/openwrt.git;openwrt-24.10
src-git packages https://git.openwrt.org/feed/packages.git;openwrt-24.10
src-git luci https://git.openwrt.org/project/luci.git;openwrt-24.10
src-git kiddin9 https://github.com/opewrt/kwrt-packages.git^f5cbc4bdd62ad549f587e8753e36aa4c307cfb2f
