src-git-full base https://git.openwrt.org/openwrt/openwrt.git;openwrt-24.10
src-git packages https://github.com/opewrt/openwrt-packages.git;kwrt-24.10
src-git luci https://github.com/opewrt/openwrt-luci.git;kwrt-24.10
src-git routing https://github.com/opewrt/openwrt-routing.git;kwrt-24.10
src-git kiddin9 https://github.com/opewrt/kwrt-packages.git;openwrt-24.10
