include $(TOPDIR)/rules.mk

PKG_NAME:=bad-branch
PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/example/bad-branch.git
PKG_SOURCE_VERSION:=refs/heads/release
PKG_MIRROR_HASH:=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
